# -*- coding: utf-8 -*-
#
# Picmonic Anki Addon Add-on for Anki
# Copyright (C)  2021 Picmonic <https://www.picmonic.com>
#
# This file was automatically generated by Anki Add-on Builder v0.1.4
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "onboarding",
    "settings"
]

from . import onboarding
from . import settings
