# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(381, 196)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setGeometry(QtCore.QRect(10, 160, 361, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Settings)
        self.label.setGeometry(QtCore.QRect(10, 10, 361, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.logoOpacity = QtWidgets.QSlider(Settings)
        self.logoOpacity.setGeometry(QtCore.QRect(170, 130, 191, 22))
        self.logoOpacity.setMaximum(10)
        self.logoOpacity.setProperty("value", 8)
        self.logoOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.logoOpacity.setObjectName("logoOpacity")
        self.marketId = QtWidgets.QComboBox(Settings)
        self.marketId.setGeometry(QtCore.QRect(170, 40, 191, 26))
        self.marketId.setCurrentText("")
        self.marketId.setObjectName("marketId")
        self.label_3 = QtWidgets.QLabel(Settings)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Settings)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Settings)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 151, 16))
        self.label_5.setObjectName("label_5")
        self.whenPopupConflictsShowLogo = QtWidgets.QCheckBox(Settings)
        self.whenPopupConflictsShowLogo.setGeometry(QtCore.QRect(10, 100, 361, 20))
        self.whenPopupConflictsShowLogo.setObjectName("whenPopupConflictsShowLogo")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Settings)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 70, 191, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.underlineColorContainer = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.underlineColorContainer.setContentsMargins(0, 0, 0, 0)
        self.underlineColorContainer.setObjectName("underlineColorContainer")

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.label.setText(_translate("Settings", "Add-On Settings"))
        self.label_3.setText(_translate("Settings", "Area of Study"))
        self.label_4.setText(_translate("Settings", "Underline Color"))
        self.label_5.setText(_translate("Settings", "Logo Opacity"))
        self.whenPopupConflictsShowLogo.setText(_translate("Settings", "Show logo when another add-on conflicts"))
